extends: default

rules:
  line-length:
    max: 120
    level: warning
  trailing-spaces: enable
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1
  brackets: enable
  colons: enable
  commas: enable
  comments:
    min-spaces-from-content: 1
  comments-indentation: enable
  document-end: disable
  document-start: disable
  float-values: enable
  hyphens: enable
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  key-duplicates: enable
  key-ordering: disable
  new-line-at-end-of-file: enable
  octal-values: enable
  quoted-strings:
    quote-type: single
    required: only-when-needed
  truthy:
    allowed-values: ['true', 'false']
    check-keys: true
