# cargo-deny configuration
# See: https://embarkstudios.github.io/cargo-deny/

[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[output]
feature-depth = 1

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
    # We can add specific advisories to ignore here if needed
]

[licenses]
version = 2
allow = [
    # Permissive licenses
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "0BSD",
    "Unlicense",
    
    # Weak copyleft
    "MPL-2.0",
    
    # Unicode and text-related licenses
    "Unicode-3.0",
    
    # Other common licenses
    "Zlib",
    "BSL-1.0",
    "OpenSSL",
]
exceptions = [
    # We can add specific crate exceptions here if needed
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = [
    # We can allow specific crates here if needed
]
deny = [
    # We can deny specific crates here if needed
    # { name = "openssl", version = "*" }, # Example: prefer rustls over openssl
]
skip = [
    # Skip version conflicts for these crates - common in ecosystem transitions
    { name = "windows-sys", version = ">=0.45" },
    { name = "windows_x86_64_msvc", version = ">=0.45" },
    { name = "windows-targets", version = ">=0.45" },
    { name = "windows_x86_64_gnu", version = ">=0.45" },
    
    # HTTP ecosystem transition from 0.2 to 1.0
    { name = "http", version = ">=0.2" },
    { name = "http-body", version = ">=0.4" },
    { name = "hyper", version = ">=0.14" },
    { name = "h2", version = ">=0.3" },
    
    # Base64 ecosystem has multiple active versions
    { name = "base64", version = ">=0.13" },
    
    # System configuration crates
    { name = "system-configuration", version = ">=0.5" },
    { name = "system-configuration-sys", version = ">=0.5" },
    
    # Utility crates with common version splits
    { name = "socket2", version = ">=0.5" },
    { name = "sync_wrapper", version = ">=0.1" },
    { name = "bitflags", version = ">=1.0" },
    
    # Regex ecosystem
    { name = "regex-automata", version = ">=0.1" },
    { name = "regex-syntax", version = ">=0.6" },
    
    # Random number generation (only keep active ones)
    { name = "getrandom", version = ">=0.1" },
    
    # Error handling
    { name = "thiserror", version = ">=1.0" },
    { name = "thiserror-impl", version = ">=1.0" },
    
    # TLS/crypto ecosystem transitions
    { name = "rustls", version = ">=0.21" },
    { name = "rustls-webpki", version = ">=0.101" },
    { name = "rustls-pemfile", version = ">=1.0" },
    { name = "tokio-rustls", version = ">=0.24" },
]
skip-tree = [
    # Skip entire dependency trees for these crates
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
