services:
  ferragate:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - LOG_DIR=/app/logs
      - CONFIG_PATH=/app/gateway.toml
    volumes:
      - ./gateway.toml:/app/gateway.toml:ro
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped