name: CI
permissions:
  contents: read

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "ci-cache"

      - name: Run cargo check
        run: cargo check --all-targets --all-features

  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, beta]
        exclude:
          - os: windows-latest
            rust: beta
          - os: macOS-latest
            rust: beta
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "test-cache-${{ matrix.os }}-${{ matrix.rust }}"

      - name: Run cargo test
        run: cargo test --all-features --workspace
        env:
          # Provide consistent test environment across platforms
          RUST_BACKTRACE: 1
          # Ensure consistent tempdir behavior on Windows  
          TEMP: ${{ runner.temp }}
          TMP: ${{ runner.temp }}

      - name: Run integration tests
        run: cargo test --test integration_tests --all-features
        env:
          RUST_BACKTRACE: 1

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "clippy-cache"

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        env:
          # Ensure consistent behavior across platforms
          RUST_BACKTRACE: 1

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "audit-cache"

      - name: Run cargo audit
        run: cargo audit

  cargo-deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install cargo-deny
        run: cargo install cargo-deny

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "deny-cache"

      - name: Run cargo deny
        run: cargo deny check

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview, clippy

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "sonar-cache"

      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
        env:
          RUST_BACKTRACE: 1

      - name: Generate clippy report
        run: |
          cargo clippy --all-targets --all-features --message-format=json > clippy-report.json || true

      - name: Run tests for SonarCloud
        run: cargo test --all-features --workspace
        env:
          RUST_BACKTRACE: 1

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "docs-cache"

      - name: Build documentation
        run: cargo doc --all-features --no-deps --document-private-items

      - name: Check for broken links in docs
        run: |
          cargo install cargo-deadlinks
          cargo deadlinks --check-http

  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ferragate:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "benchmark-cache"

      - name: Run benchmarks
        run: cargo bench --all-features

      - name: Upload benchmark report
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: target/criterion/
          retention-days: 30

      - name: Comment benchmark results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = './target/criterion/report/index.html';
            if (fs.existsSync(path)) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '📊 **Benchmark Results Generated**\n\nBenchmark report has been generated and uploaded as an artifact. Download the `benchmark-results` artifact to view detailed performance metrics.'
              });
            }
